### ISSUE TITLE
Add Curl as LOLBIN

### ISSUE THREAD

**Issue by biffalo** [LOLBAS-Project/LOLBAS#289]
Curl is now in Windows 10 1809 and up. Server 2019 and Server 2022. Windows 11 all versions. Since it is native to the OS and can be used for data exfil, downloading additional tooling it should likely be added to the project.
[curl.yml.txt](https://github.com/LOLBAS-Project/LOLBAS/files/11367457/curl.yml.txt)

**Comment by wietze** [comment]
Hey @biffalo , we've [previously considered](https://github.com/LOLBAS-Project/LOLBAS/pull/57#issuecomment-589648205) adding `curl`, but due to it containing expected functionality, decided against including it. I agree that the functionality is still useful for e.g. red teamers, but based on the earlier assessment, this entry would unfortunately not be the right fit for this project. For that reason I'm closing this issue now - if you think I'm wrong though please comment in here to reopen the issue.
