### ISSUE TITLE
Adding Powershell.exe to the list of LOLBins

### ISSUE THREAD

**Issue by last-byte** [LOLBAS-Project/LOLBAS#346]
As of now I don't see Powershell.exe listed in the LOLBas website, while cmd.exe is. Shouldn't it be considered a LOLBin too?

**Comment by wietze** [comment]
Hey @last-byte , thanks for making this suggestion. This has been discussed before (see https://github.com/LOLBAS-Project/LOLBAS/pull/136#issuecomment-1250056203) and we came to the conclusion that whilst `powershell` is a great tool for offensive purposes and is often used by threat actors as part of their attacks, its use is typically seen as 'expected' for this shell/scripting-type application. A [requirement](https://github.com/LOLBAS-Project/LOLBAS#criteria) for being listed as LOLBAS is having 'unexpected' functionality. 

As such, if my assessment is right, this entry would unfortunately not be the right fit for this project. For that reason I'm closing this issue fort now - if you think I'm wrong though please comment in here.

**Comment by last-byte** [comment]
I do understand the reasoning behind your decision, though I still think it should be added, given the fact cmd.exe is there too. Nevertheless, the project's yours and the decision to add something or not also is ¯\_(ツ)_/¯

**Comment by wietze** [comment]
That's a fair point, `cmd` is included because its ability to interact with Alternate Data Streams (ADS) and WebDAV servers is considered unusual. I have no doubt `powershell` can do the same, but given it's deep integration into Window's APIs I would not call this unexpected. 

As said, your input is appreciated though - it's not the first time `powershell` is proposed as an addition, so it may be added to the honorable mentions section of the repository.
